# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kuaforProfili2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 466)
        MainWindow.setMaximumSize(QtCore.QSize(500, 466))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.kisisel_bilgiler_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setBold(True)
        font.setWeight(75)
        self.kisisel_bilgiler_groupBox.setFont(font)
        self.kisisel_bilgiler_groupBox.setObjectName("kisisel_bilgiler_groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.kisisel_bilgiler_groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.profilK_isim_label = QtWidgets.QLabel(self.kisisel_bilgiler_groupBox)
        self.profilK_isim_label.setObjectName("profilK_isim_label")
        self.verticalLayout.addWidget(self.profilK_isim_label)
        self.profilK_isim_lineEdit = QtWidgets.QLineEdit(self.kisisel_bilgiler_groupBox)
        self.profilK_isim_lineEdit.setObjectName("profilK_isim_lineEdit")
        self.verticalLayout.addWidget(self.profilK_isim_lineEdit)
        self.profilK_soyisim_label = QtWidgets.QLabel(self.kisisel_bilgiler_groupBox)
        self.profilK_soyisim_label.setObjectName("profilK_soyisim_label")
        self.verticalLayout.addWidget(self.profilK_soyisim_label)
        self.profilK_soyisim_lineEdit = QtWidgets.QLineEdit(self.kisisel_bilgiler_groupBox)
        self.profilK_soyisim_lineEdit.setObjectName("profilK_soyisim_lineEdit")
        self.verticalLayout.addWidget(self.profilK_soyisim_lineEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.isletme_bilgileri_groupBox = QtWidgets.QGroupBox(self.kisisel_bilgiler_groupBox)
        self.isletme_bilgileri_groupBox.setMinimumSize(QtCore.QSize(0, 200))
        self.isletme_bilgileri_groupBox.setMaximumSize(QtCore.QSize(500, 600))
        self.isletme_bilgileri_groupBox.setObjectName("isletme_bilgileri_groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.isletme_bilgileri_groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.isletmeEposta_label = QtWidgets.QLabel(self.isletme_bilgileri_groupBox)
        self.isletmeEposta_label.setObjectName("isletmeEposta_label")
        self.gridLayout_2.addWidget(self.isletmeEposta_label, 1, 0, 1, 1)
        self.isletmeAdi_label = QtWidgets.QLabel(self.isletme_bilgileri_groupBox)
        self.isletmeAdi_label.setObjectName("isletmeAdi_label")
        self.gridLayout_2.addWidget(self.isletmeAdi_label, 0, 0, 1, 1)
        self.sifreDegistir_label = QtWidgets.QLabel(self.isletme_bilgileri_groupBox)
        self.sifreDegistir_label.setObjectName("sifreDegistir_label")
        self.gridLayout_2.addWidget(self.sifreDegistir_label, 5, 0, 1, 1)
        self.isletme_ilce_label = QtWidgets.QLabel(self.isletme_bilgileri_groupBox)
        self.isletme_ilce_label.setObjectName("isletme_ilce_label")
        self.gridLayout_2.addWidget(self.isletme_ilce_label, 4, 0, 1, 1)
        self.isletmeTel_label = QtWidgets.QLabel(self.isletme_bilgileri_groupBox)
        self.isletmeTel_label.setObjectName("isletmeTel_label")
        self.gridLayout_2.addWidget(self.isletmeTel_label, 2, 0, 1, 1)
        self.SifreDegistir_lineEdit = QtWidgets.QLineEdit(self.isletme_bilgileri_groupBox)
        self.SifreDegistir_lineEdit.setObjectName("SifreDegistir_lineEdit")
        self.gridLayout_2.addWidget(self.SifreDegistir_lineEdit, 5, 2, 1, 1)
        self.isletme_ilce_lineEdit = QtWidgets.QLineEdit(self.isletme_bilgileri_groupBox)
        self.isletme_ilce_lineEdit.setObjectName("isletme_ilce_lineEdit")
        self.gridLayout_2.addWidget(self.isletme_ilce_lineEdit, 4, 2, 1, 1)
        self.isletmeTel_lineEdit = QtWidgets.QLineEdit(self.isletme_bilgileri_groupBox)
        self.isletmeTel_lineEdit.setObjectName("isletmeTel_lineEdit")
        self.gridLayout_2.addWidget(self.isletmeTel_lineEdit, 2, 2, 1, 1)
        self.isletmeEposta_lineEdit = QtWidgets.QLineEdit(self.isletme_bilgileri_groupBox)
        self.isletmeEposta_lineEdit.setObjectName("isletmeEposta_lineEdit")
        self.gridLayout_2.addWidget(self.isletmeEposta_lineEdit, 1, 2, 1, 1)
        self.isletmeAdi_lineEdit = QtWidgets.QLineEdit(self.isletme_bilgileri_groupBox)
        self.isletmeAdi_lineEdit.setObjectName("isletmeAdi_lineEdit")
        self.gridLayout_2.addWidget(self.isletmeAdi_lineEdit, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.isletme_bilgileri_groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.bilgilerimiKaydet_pushButton = QtWidgets.QPushButton(self.kisisel_bilgiler_groupBox)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.bilgilerimiKaydet_pushButton.setFont(font)
        self.bilgilerimiKaydet_pushButton.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(245, 167, 255);\n"
"border: none;\n"
"padding: 10px 20px;\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #333333;\n"
"border: 1px solid black;\n"
"}")
        self.bilgilerimiKaydet_pushButton.setObjectName("bilgilerimiKaydet_pushButton")
        self.verticalLayout.addWidget(self.bilgilerimiKaydet_pushButton)
        self.gridLayout.addWidget(self.kisisel_bilgiler_groupBox, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 26))
        self.menubar.setObjectName("menubar")
        self.menuOturumu_Kapat = QtWidgets.QMenu(self.menubar)
        self.menuOturumu_Kapat.setObjectName("menuOturumu_Kapat")
        self.menuAna_Sayfaya_Don = QtWidgets.QMenu(self.menubar)
        self.menuAna_Sayfaya_Don.setObjectName("menuAna_Sayfaya_Don")
        self.menuHesab_mi_Sil = QtWidgets.QMenu(self.menubar)
        self.menuHesab_mi_Sil.setObjectName("menuHesab_mi_Sil")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAna_Sayfaya_Don.menuAction())
        self.menubar.addAction(self.menuOturumu_Kapat.menuAction())
        self.menubar.addAction(self.menuHesab_mi_Sil.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.kisisel_bilgiler_groupBox.setTitle(_translate("MainWindow", "Kişisel Bilgiler"))
        self.profilK_isim_label.setText(_translate("MainWindow", "İsim:"))
        self.profilK_soyisim_label.setText(_translate("MainWindow", "Soyisim:"))
        self.isletme_bilgileri_groupBox.setTitle(_translate("MainWindow", "İşletme Bilgileri"))
        self.isletmeEposta_label.setText(_translate("MainWindow", "E-posta:"))
        self.isletmeAdi_label.setText(_translate("MainWindow", "İşletme Adı:"))
        self.sifreDegistir_label.setText(_translate("MainWindow", "Şifre Değiştir:"))
        self.isletme_ilce_label.setText(_translate("MainWindow", "İlçe:"))
        self.isletmeTel_label.setText(_translate("MainWindow", "Telefon:"))
        self.bilgilerimiKaydet_pushButton.setText(_translate("MainWindow", "BİLGİLERİMİ KAYDET"))
        self.menuOturumu_Kapat.setTitle(_translate("MainWindow", "Oturumu Kapat"))
        self.menuAna_Sayfaya_Don.setTitle(_translate("MainWindow", "Ana Sayfaya Dön"))
        self.menuHesab_mi_Sil.setTitle(_translate("MainWindow", "Hesabımı Sil"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
