# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'musteriProfili.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 460)
        MainWindow.setMaximumSize(QtCore.QSize(500, 480))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.m_kisisel_bilgiler_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.m_kisisel_bilgiler_groupBox.setGeometry(QtCore.QRect(10, 0, 481, 391))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setBold(True)
        font.setWeight(75)
        self.m_kisisel_bilgiler_groupBox.setFont(font)
        self.m_kisisel_bilgiler_groupBox.setObjectName("m_kisisel_bilgiler_groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.m_kisisel_bilgiler_groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.profilM_isim_label = QtWidgets.QLabel(self.m_kisisel_bilgiler_groupBox)
        self.profilM_isim_label.setObjectName("profilM_isim_label")
        self.verticalLayout.addWidget(self.profilM_isim_label)
        self.profilM_isim_lineEdit = QtWidgets.QLineEdit(self.m_kisisel_bilgiler_groupBox)
        self.profilM_isim_lineEdit.setStyleSheet("")
        self.profilM_isim_lineEdit.setObjectName("profilM_isim_lineEdit")
        self.verticalLayout.addWidget(self.profilM_isim_lineEdit)
        self.profilM_soyisim_label = QtWidgets.QLabel(self.m_kisisel_bilgiler_groupBox)
        self.profilM_soyisim_label.setObjectName("profilM_soyisim_label")
        self.verticalLayout.addWidget(self.profilM_soyisim_label)
        self.profilM_soyisim_lineEdit = QtWidgets.QLineEdit(self.m_kisisel_bilgiler_groupBox)
        self.profilM_soyisim_lineEdit.setStyleSheet("")
        self.profilM_soyisim_lineEdit.setObjectName("profilM_soyisim_lineEdit")
        self.verticalLayout.addWidget(self.profilM_soyisim_lineEdit)
        self.musteri_ilce_label = QtWidgets.QLabel(self.m_kisisel_bilgiler_groupBox)
        self.musteri_ilce_label.setObjectName("musteri_ilce_label")
        self.verticalLayout.addWidget(self.musteri_ilce_label)
        self.musteri_ilce_lineEdit = QtWidgets.QLineEdit(self.m_kisisel_bilgiler_groupBox)
        self.musteri_ilce_lineEdit.setStyleSheet("")
        self.musteri_ilce_lineEdit.setObjectName("musteri_ilce_lineEdit")
        self.verticalLayout.addWidget(self.musteri_ilce_lineEdit)
        self.musteri_Tel_label = QtWidgets.QLabel(self.m_kisisel_bilgiler_groupBox)
        self.musteri_Tel_label.setObjectName("musteri_Tel_label")
        self.verticalLayout.addWidget(self.musteri_Tel_label)
        self.musteri_Tel_lineEdit = QtWidgets.QLineEdit(self.m_kisisel_bilgiler_groupBox)
        self.musteri_Tel_lineEdit.setStyleSheet("")
        self.musteri_Tel_lineEdit.setObjectName("musteri_Tel_lineEdit")
        self.verticalLayout.addWidget(self.musteri_Tel_lineEdit)
        self.musteri_Eposta_label = QtWidgets.QLabel(self.m_kisisel_bilgiler_groupBox)
        self.musteri_Eposta_label.setObjectName("musteri_Eposta_label")
        self.verticalLayout.addWidget(self.musteri_Eposta_label)
        self.musteri_Eposta_lineEdit = QtWidgets.QLineEdit(self.m_kisisel_bilgiler_groupBox)
        self.musteri_Eposta_lineEdit.setStyleSheet("")
        self.musteri_Eposta_lineEdit.setObjectName("musteri_Eposta_lineEdit")
        self.verticalLayout.addWidget(self.musteri_Eposta_lineEdit)
        self.musteri_SifreDegistir_label = QtWidgets.QLabel(self.m_kisisel_bilgiler_groupBox)
        self.musteri_SifreDegistir_label.setObjectName("musteri_SifreDegistir_label")
        self.verticalLayout.addWidget(self.musteri_SifreDegistir_label)
        self.musteri_SifreDegistir_lineEdit = QtWidgets.QLineEdit(self.m_kisisel_bilgiler_groupBox)
        self.musteri_SifreDegistir_lineEdit.setStyleSheet("")
        self.musteri_SifreDegistir_lineEdit.setObjectName("musteri_SifreDegistir_lineEdit")
        self.verticalLayout.addWidget(self.musteri_SifreDegistir_lineEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.m_bilgilerimiKaydet_pushButton = QtWidgets.QPushButton(self.m_kisisel_bilgiler_groupBox)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.m_bilgilerimiKaydet_pushButton.setFont(font)
        self.m_bilgilerimiKaydet_pushButton.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(245, 167, 255);\n"
"border: none;\n"
"padding: 10px 20px;\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #333333;\n"
"border: 1px solid black;\n"
"}")
        self.m_bilgilerimiKaydet_pushButton.setObjectName("m_bilgilerimiKaydet_pushButton")
        self.verticalLayout.addWidget(self.m_bilgilerimiKaydet_pushButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 26))
        self.menubar.setObjectName("menubar")
        self.menuAna_Sayfaya_Don = QtWidgets.QMenu(self.menubar)
        self.menuAna_Sayfaya_Don.setObjectName("menuAna_Sayfaya_Don")
        self.menuOturumu_Kapat = QtWidgets.QMenu(self.menubar)
        self.menuOturumu_Kapat.setObjectName("menuOturumu_Kapat")
        self.menuHesab_m_Sil = QtWidgets.QMenu(self.menubar)
        self.menuHesab_m_Sil.setObjectName("menuHesab_m_Sil")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAna_Sayfaya_Don.menuAction())
        self.menubar.addAction(self.menuOturumu_Kapat.menuAction())
        self.menubar.addAction(self.menuHesab_m_Sil.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.m_kisisel_bilgiler_groupBox.setTitle(_translate("MainWindow", "Kişisel Bilgiler"))
        self.profilM_isim_label.setText(_translate("MainWindow", "İsim:"))
        self.profilM_soyisim_label.setText(_translate("MainWindow", "Soyisim:"))
        self.musteri_ilce_label.setText(_translate("MainWindow", "İlçe:"))
        self.musteri_Tel_label.setText(_translate("MainWindow", "Telefon:"))
        self.musteri_Eposta_label.setText(_translate("MainWindow", "E-posta:"))
        self.musteri_SifreDegistir_label.setText(_translate("MainWindow", "Şifre Değiştir:"))
        self.m_bilgilerimiKaydet_pushButton.setText(_translate("MainWindow", "BİLGİLERİMİ KAYDET"))
        self.menuAna_Sayfaya_Don.setTitle(_translate("MainWindow", "Ana Sayfaya Don"))
        self.menuOturumu_Kapat.setTitle(_translate("MainWindow", "Oturumu Kapat"))
        self.menuHesab_m_Sil.setTitle(_translate("MainWindow", "Hesabımı Sil"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
